### ISSUE TITLE
Implement Server Side of Instance Registry API

### ISSUE THREAD

**Issue by Ayybeeshafi** [delphi-hub/delphi-registry#5]

**Comment by Ayybeeshafi** [comment]
@johannesduesing I have uploaded the server side on a branch `instance-registry-api-server`. The server is running. There is a need to implement the functionality in the methods that will be accepting the arguments from the client side.

**Comment by johannesduesing** [comment]
Hey @Ayybeeshafi , thanks for the work, it does look good for now. I will try to extend that branch so that the JSON serialization is used and the actual Instace-Objects can be accepted as parameters. For now i would like to assign you to #6 , because it involves changing the OpenAPI specification you created.

**Comment by johannesduesing** [comment]
API fully implemented in #7
